# Generated by Django 6.0.6 on 2026-06-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailplausible', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plausiblesettings',
            name='plausible_domain',
        ),
        migrations.RemoveField(
            model_name='plausiblesettings',
            name='script_name',
        ),
        migrations.RemoveField(
            model_name='plausiblesettings',
            name='site_domain',
        ),
        migrations.AddField(
            model_name='plausiblesettings',
            name='script_url',
            field=models.URLField(blank=True, help_text='Full Plausible script URL, e.g. https://plausible.io/js/pa-XXXXXXXX.js', max_length=500),
        ),
    ]
